remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "neon"
masthead_title: "Open Blockchain for Asset Disposition Architecture"
layout: splash
title: OBADA
description: The Open Blockchain for Asset Disposition Architecture
url: "https://www.obada.io/"
logo: "/assets/logo/obada-logo-light-gradient.svg"
has_toc: false
search_enabled: false
footer_content: "Open Blockchain for Asset Disposition Architecture (OBADA)"
plugins: ['jekyll-include-cache']
